source :rubygems

# PostgreSQL driver
gem 'pg'

# Sinatra driver
gem 'sinatra'
gem 'sinatra-contrib'

gem 'carrierwave'
gem 'carrierwave-datamapper', :require => 'carrierwave/datamapper'

# Use Thin for our web server
gem 'thin'

gem 'activesupport'
gem 'activerecord'

gem 'rake'

group :test do
  gem 'faker'
  gem 'rspec'
end
